# CircleCI configuration file
version: 2.1

jobs:
  build:
    docker:
      - image: cimg/node:21.6.2
    steps:
      - checkout
      - run: echo "npm installing"
      - run: npm install
      - run: CI=true npm run build
  test:
    docker:
      - image: cimg/node:21.6.2
    steps:
      - checkout
      - run: echo "running tests"
      - run: npm install
      - run: npm test
  exampleTest:
    docker:
      - image: cimg/node:21.6.2
    steps:
      - checkout
      - run: echo "Testing"
workflows:
  version: 2.1
  build_and_test_lint:
    jobs:
      - build
      - exampleTest
      - test:
          requires:
            - exampleTest
